name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: gox
      run: |
        go get -u github.com/mitchellh/gox
        gox -os="linux darwin windows" -arch="amd64" -output="dist/adrs_{{.OS}}"
        cd dist/ && gzip -k *

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
